### ISSUE TITLE
Add value block?

### ISSUE THREAD

**Issue by theDanielJLewis** [Lehmancreations/Podcast-Namespace-Wordpress-Plugin#5]
I finally got around to installing this, because I wanted to add the value block to my feed, but now I see it's not supported.

But I also know this tag is not entirely finalized, yet, and the interface necessary for it could get more complicated since you would need the ability to add multiple recipients.

I look forward to when it can be supported!

**Comment by Lehmancreations** [comment]
This has been added in version 1.5
