### ISSUE TITLE
Disclose that you're taking a cut with <podcast:value>

### ISSUE THREAD

**Issue by theDanielJLewis** [Lehmancreations/Podcast-Namespace-Wordpress-Plugin#6]
I just noticed that regardless of whether I enter my own value recipient or leave it blank, there's a `<podcast:valueRecipient>` for you in the code, and that's not prominently disclosed.

This would mean that if someone does _not_ populate the value recipient, you're getting 100% of their earnings.

And not prominently disclosing that you're taking anything seems a little slimy.

**Comment by Lehmancreations** [comment]
Daniel, This is not the intended action and I tested last night and if I do not put anything in that input then there is no value block at all in the feed, including my split. I have also disclosed on the form that if you put something in there I add a 1% fee split in the block. 

The disclosure is part of release 1.5.4 which was just published
